# Generated by Django 4.0.6 on 2022-08-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatthememe', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game_card',
            unique_together=set(),
        ),
    ]
